export const COUNTRIES = [
  {
    code: "US",
    name: "United States",
    currency: "USD",
    symbol: "$",
    taxName: "Sales Tax",
    defaultTaxRate: 0,
  },
  {
    code: "GB",
    name: "United Kingdom",
    currency: "GBP",
    symbol: "£",
    taxName: "VAT",
    defaultTaxRate: 20,
  },
  {
    code: "EU",
    name: "European Union",
    currency: "EUR",
    symbol: "€",
    taxName: "VAT",
    defaultTaxRate: 21,
  },
  { code: "IN", name: "India", currency: "INR", symbol: "₹", taxName: "GST", defaultTaxRate: 18 },
  {
    code: "CA",
    name: "Canada",
    currency: "CAD",
    symbol: "C$",
    taxName: "GST/HST",
    defaultTaxRate: 5,
  },
  {
    code: "AU",
    name: "Australia",
    currency: "AUD",
    symbol: "A$",
    taxName: "GST",
    defaultTaxRate: 10,
  },
  {
    code: "JP",
    name: "Japan",
    currency: "JPY",
    symbol: "¥",
    taxName: "Consumption Tax",
    defaultTaxRate: 10,
  },
  {
    code: "CUSTOM",
    name: "Custom Setup",
    currency: "USD",
    symbol: "$",
    taxName: "Tax",
    defaultTaxRate: 0,
  },
];
