export const COUNTRIES = [
  {
    code: "AF",
    country: "Afghanistan",
    name: "Afghanistan (؋)",
    currency: "AFN",
    symbol: "؋",
  },
  {
    code: "AX",
    country: "Åland Islands",
    name: "Åland Islands (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "AL",
    country: "Albania",
    name: "Albania (L)",
    currency: "ALL",
    symbol: "L",
  },
  {
    code: "DZ",
    country: "Algeria",
    name: "Algeria (DZD)",
    currency: "DZD",
    symbol: "DZD",
  },
  {
    code: "AS",
    country: "American Samoa",
    name: "American Samoa ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "AD",
    country: "Andorra",
    name: "Andorra (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "AO",
    country: "Angola",
    name: "Angola (AOA)",
    currency: "AOA",
    symbol: "AOA",
  },
  {
    code: "AI",
    country: "Anguilla",
    name: "Anguilla ($)",
    currency: "XCD",
    symbol: "$",
  },
  {
    code: "AG",
    country: "Antigua And Barbuda",
    name: "Antigua And Barbuda ($)",
    currency: "XCD",
    symbol: "$",
  },
  {
    code: "AR",
    country: "Argentina",
    name: "Argentina ($)",
    currency: "ARS",
    symbol: "$",
  },
  {
    code: "AM",
    country: "Armenia",
    name: "Armenia (AMD)",
    currency: "AMD",
    symbol: "AMD",
  },
  {
    code: "AW",
    country: "Aruba",
    name: "Aruba (ƒ)",
    currency: "AWG",
    symbol: "ƒ",
  },
  {
    code: "AU",
    country: "Australia",
    name: "Australia ($)",
    currency: "AUD",
    symbol: "$",
  },
  {
    code: "AT",
    country: "Austria",
    name: "Austria (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "AZ",
    country: "Azerbaijan",
    name: "Azerbaijan (₼)",
    currency: "AZN",
    symbol: "₼",
  },
  {
    code: "BS",
    country: "Bahamas",
    name: "Bahamas ($)",
    currency: "BSD",
    symbol: "$",
  },
  {
    code: "BH",
    country: "Bahrain",
    name: "Bahrain (BHD)",
    currency: "BHD",
    symbol: "BHD",
  },
  {
    code: "BD",
    country: "Bangladesh",
    name: "Bangladesh (BDT)",
    currency: "BDT",
    symbol: "BDT",
  },
  {
    code: "BB",
    country: "Barbados",
    name: "Barbados ($)",
    currency: "BBD",
    symbol: "$",
  },
  {
    code: "BY",
    country: "Belarus",
    name: "Belarus (p.)",
    currency: "BYR",
    symbol: "p.",
  },
  {
    code: "BE",
    country: "Belgium",
    name: "Belgium (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "BZ",
    country: "Belize",
    name: "Belize (BZ$)",
    currency: "BZD",
    symbol: "BZ$",
  },
  {
    code: "BJ",
    country: "Benin",
    name: "Benin (XOF)",
    currency: "XOF",
    symbol: "XOF",
  },
  {
    code: "BM",
    country: "Bermuda",
    name: "Bermuda ($)",
    currency: "BMD",
    symbol: "$",
  },
  {
    code: "BT",
    country: "Bhutan",
    name: "Bhutan (₹)",
    currency: "INR",
    symbol: "₹",
  },
  {
    code: "BO",
    country: "Bolivia, Plurinational State Of",
    name: "Bolivia, Plurinational State Of (Bs.)",
    currency: "BOB",
    symbol: "Bs.",
  },
  {
    code: "BQ",
    country: "Bonaire, Saint Eustatius And Saba",
    name: "Bonaire, Saint Eustatius And Saba ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "BA",
    country: "Bosnia & Herzegovina",
    name: "Bosnia & Herzegovina (KM)",
    currency: "BAM",
    symbol: "KM",
  },
  {
    code: "BW",
    country: "Botswana",
    name: "Botswana (P)",
    currency: "BWP",
    symbol: "P",
  },
  {
    code: "BV",
    country: "Bouvet Island",
    name: "Bouvet Island (kr)",
    currency: "NOK",
    symbol: "kr",
  },
  {
    code: "BR",
    country: "Brazil",
    name: "Brazil (R$)",
    currency: "BRL",
    symbol: "R$",
  },
  {
    code: "IO",
    country: "British Indian Ocean Territory",
    name: "British Indian Ocean Territory ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "BN",
    country: "Brunei Darussalam",
    name: "Brunei Darussalam ($)",
    currency: "BND",
    symbol: "$",
  },
  {
    code: "BG",
    country: "Bulgaria",
    name: "Bulgaria (лв)",
    currency: "BGN",
    symbol: "лв",
  },
  {
    code: "BF",
    country: "Burkina Faso",
    name: "Burkina Faso (XOF)",
    currency: "XOF",
    symbol: "XOF",
  },
  {
    code: "BI",
    country: "Burundi",
    name: "Burundi (BIF)",
    currency: "BIF",
    symbol: "BIF",
  },
  {
    code: "CV",
    country: "Cabo Verde",
    name: "Cabo Verde (CVE)",
    currency: "CVE",
    symbol: "CVE",
  },
  {
    code: "KH",
    country: "Cambodia",
    name: "Cambodia (៛)",
    currency: "KHR",
    symbol: "៛",
  },
  {
    code: "CM",
    country: "Cameroon",
    name: "Cameroon (XAF)",
    currency: "XAF",
    symbol: "XAF",
  },
  {
    code: "CA",
    country: "Canada",
    name: "Canada ($)",
    currency: "CAD",
    symbol: "$",
  },
  {
    code: "KY",
    country: "Cayman Islands",
    name: "Cayman Islands ($)",
    currency: "KYD",
    symbol: "$",
  },
  {
    code: "CF",
    country: "Central African Republic",
    name: "Central African Republic (XAF)",
    currency: "XAF",
    symbol: "XAF",
  },
  {
    code: "TD",
    country: "Chad",
    name: "Chad (XAF)",
    currency: "XAF",
    symbol: "XAF",
  },
  {
    code: "CL",
    country: "Chile",
    name: "Chile ($)",
    currency: "CLP",
    symbol: "$",
  },
  {
    code: "CN",
    country: "China",
    name: "China (¥)",
    currency: "CNY",
    symbol: "¥",
  },
  {
    code: "CX",
    country: "Christmas Island",
    name: "Christmas Island ($)",
    currency: "AUD",
    symbol: "$",
  },
  {
    code: "CC",
    country: "Cocos (Keeling) Islands",
    name: "Cocos (Keeling) Islands ($)",
    currency: "AUD",
    symbol: "$",
  },
  {
    code: "CO",
    country: "Colombia",
    name: "Colombia ($)",
    currency: "COP",
    symbol: "$",
  },
  {
    code: "KM",
    country: "Comoros",
    name: "Comoros (KMF)",
    currency: "KMF",
    symbol: "KMF",
  },
  {
    code: "CK",
    country: "Cook Islands",
    name: "Cook Islands ($)",
    currency: "NZD",
    symbol: "$",
  },
  {
    code: "CR",
    country: "Costa Rica",
    name: "Costa Rica (₡)",
    currency: "CRC",
    symbol: "₡",
  },
  {
    code: "CI",
    country: "Côte d'Ivoire",
    name: "Côte d'Ivoire (XOF)",
    currency: "XOF",
    symbol: "XOF",
  },
  {
    code: "HR",
    country: "Croatia",
    name: "Croatia (kn)",
    currency: "HRK",
    symbol: "kn",
  },
  {
    code: "CU",
    country: "Cuba",
    name: "Cuba (₱)",
    currency: "CUP",
    symbol: "₱",
  },
  {
    code: "CW",
    country: "Curacao",
    name: "Curacao (ƒ)",
    currency: "ANG",
    symbol: "ƒ",
  },
  {
    code: "CY",
    country: "Cyprus",
    name: "Cyprus (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "CZ",
    country: "Czech Republic",
    name: "Czech Republic (Kč)",
    currency: "CZK",
    symbol: "Kč",
  },
  {
    code: "CD",
    country: "Democratic Republic Of Congo",
    name: "Democratic Republic Of Congo (CDF)",
    currency: "CDF",
    symbol: "CDF",
  },
  {
    code: "DK",
    country: "Denmark",
    name: "Denmark (kr)",
    currency: "DKK",
    symbol: "kr",
  },
  {
    code: "DJ",
    country: "Djibouti",
    name: "Djibouti (DJF)",
    currency: "DJF",
    symbol: "DJF",
  },
  {
    code: "DM",
    country: "Dominica",
    name: "Dominica ($)",
    currency: "XCD",
    symbol: "$",
  },
  {
    code: "DO",
    country: "Dominican Republic",
    name: "Dominican Republic (RD$)",
    currency: "DOP",
    symbol: "RD$",
  },
  {
    code: "EC",
    country: "Ecuador",
    name: "Ecuador ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "EG",
    country: "Egypt",
    name: "Egypt (£)",
    currency: "EGP",
    symbol: "£",
  },
  {
    code: "SV",
    country: "El Salvador",
    name: "El Salvador ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "GQ",
    country: "Equatorial Guinea",
    name: "Equatorial Guinea (XAF)",
    currency: "XAF",
    symbol: "XAF",
  },
  {
    code: "ER",
    country: "Eritrea",
    name: "Eritrea (ERN)",
    currency: "ERN",
    symbol: "ERN",
  },
  {
    code: "EE",
    country: "Estonia",
    name: "Estonia (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "ET",
    country: "Ethiopia",
    name: "Ethiopia (ETB)",
    currency: "ETB",
    symbol: "ETB",
  },
  {
    code: "FK",
    country: "Falkland Islands",
    name: "Falkland Islands (£)",
    currency: "FKP",
    symbol: "£",
  },
  {
    code: "FO",
    country: "Faroe Islands",
    name: "Faroe Islands (kr)",
    currency: "DKK",
    symbol: "kr",
  },
  {
    code: "FJ",
    country: "Fiji",
    name: "Fiji ($)",
    currency: "FJD",
    symbol: "$",
  },
  {
    code: "FI",
    country: "Finland",
    name: "Finland (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "FR",
    country: "France",
    name: "France (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "GF",
    country: "French Guiana",
    name: "French Guiana (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "PF",
    country: "French Polynesia",
    name: "French Polynesia (XPF)",
    currency: "XPF",
    symbol: "XPF",
  },
  {
    code: "TF",
    country: "French Southern Territories",
    name: "French Southern Territories (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "GA",
    country: "Gabon",
    name: "Gabon (XAF)",
    currency: "XAF",
    symbol: "XAF",
  },
  {
    code: "GM",
    country: "Gambia",
    name: "Gambia (GMD)",
    currency: "GMD",
    symbol: "GMD",
  },
  {
    code: "GE",
    country: "Georgia",
    name: "Georgia (GEL)",
    currency: "GEL",
    symbol: "GEL",
  },
  {
    code: "DE",
    country: "Germany",
    name: "Germany (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "GH",
    country: "Ghana",
    name: "Ghana (GHS)",
    currency: "GHS",
    symbol: "GHS",
  },
  {
    code: "GI",
    country: "Gibraltar",
    name: "Gibraltar (£)",
    currency: "GIP",
    symbol: "£",
  },
  {
    code: "GR",
    country: "Greece",
    name: "Greece (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "GL",
    country: "Greenland",
    name: "Greenland (kr)",
    currency: "DKK",
    symbol: "kr",
  },
  {
    code: "GD",
    country: "Grenada",
    name: "Grenada ($)",
    currency: "XCD",
    symbol: "$",
  },
  {
    code: "GP",
    country: "Guadeloupe",
    name: "Guadeloupe (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "GU",
    country: "Guam",
    name: "Guam ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "GT",
    country: "Guatemala",
    name: "Guatemala (Q)",
    currency: "GTQ",
    symbol: "Q",
  },
  {
    code: "GG",
    country: "Guernsey",
    name: "Guernsey (£)",
    currency: "GBP",
    symbol: "£",
  },
  {
    code: "GN",
    country: "Guinea",
    name: "Guinea (GNF)",
    currency: "GNF",
    symbol: "GNF",
  },
  {
    code: "GW",
    country: "Guinea-bissau",
    name: "Guinea-bissau (XOF)",
    currency: "XOF",
    symbol: "XOF",
  },
  {
    code: "GY",
    country: "Guyana",
    name: "Guyana ($)",
    currency: "GYD",
    symbol: "$",
  },
  {
    code: "HT",
    country: "Haiti",
    name: "Haiti (HTG)",
    currency: "HTG",
    symbol: "HTG",
  },
  {
    code: "HM",
    country: "Heard Island And McDonald Islands",
    name: "Heard Island And McDonald Islands ($)",
    currency: "AUD",
    symbol: "$",
  },
  {
    code: "HN",
    country: "Honduras",
    name: "Honduras (L)",
    currency: "HNL",
    symbol: "L",
  },
  {
    code: "HK",
    country: "Hong Kong",
    name: "Hong Kong ($)",
    currency: "HKD",
    symbol: "$",
  },
  {
    code: "HU",
    country: "Hungary",
    name: "Hungary (Ft)",
    currency: "HUF",
    symbol: "Ft",
  },
  {
    code: "IS",
    country: "Iceland",
    name: "Iceland (kr)",
    currency: "ISK",
    symbol: "kr",
  },
  {
    code: "IN",
    country: "India",
    name: "India (₹)",
    currency: "INR",
    symbol: "₹",
  },
  {
    code: "ID",
    country: "Indonesia",
    name: "Indonesia (Rp)",
    currency: "IDR",
    symbol: "Rp",
  },
  {
    code: "IR",
    country: "Iran, Islamic Republic Of",
    name: "Iran, Islamic Republic Of (﷼)",
    currency: "IRR",
    symbol: "﷼",
  },
  {
    code: "IQ",
    country: "Iraq",
    name: "Iraq (IQD)",
    currency: "IQD",
    symbol: "IQD",
  },
  {
    code: "IE",
    country: "Ireland",
    name: "Ireland (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "IM",
    country: "Isle Of Man",
    name: "Isle Of Man (£)",
    currency: "GBP",
    symbol: "£",
  },
  {
    code: "IL",
    country: "Israel",
    name: "Israel (₪)",
    currency: "ILS",
    symbol: "₪",
  },
  {
    code: "IT",
    country: "Italy",
    name: "Italy (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "JM",
    country: "Jamaica",
    name: "Jamaica (J$)",
    currency: "JMD",
    symbol: "J$",
  },
  {
    code: "JP",
    country: "Japan",
    name: "Japan (¥)",
    currency: "JPY",
    symbol: "¥",
  },
  {
    code: "JE",
    country: "Jersey",
    name: "Jersey (£)",
    currency: "GBP",
    symbol: "£",
  },
  {
    code: "JO",
    country: "Jordan",
    name: "Jordan (JOD)",
    currency: "JOD",
    symbol: "JOD",
  },
  {
    code: "KZ",
    country: "Kazakhstan",
    name: "Kazakhstan (лв)",
    currency: "KZT",
    symbol: "лв",
  },
  {
    code: "KE",
    country: "Kenya",
    name: "Kenya (KSh)",
    currency: "KES",
    symbol: "KSh",
  },
  {
    code: "KI",
    country: "Kiribati",
    name: "Kiribati ($)",
    currency: "AUD",
    symbol: "$",
  },
  {
    code: "KP",
    country: "Korea, Democratic People's Republic Of",
    name: "Korea, Democratic People's Republic Of (₩)",
    currency: "KPW",
    symbol: "₩",
  },
  {
    code: "KR",
    country: "Korea, Republic Of",
    name: "Korea, Republic Of (₩)",
    currency: "KRW",
    symbol: "₩",
  },
  {
    code: "KW",
    country: "Kuwait",
    name: "Kuwait (KWD)",
    currency: "KWD",
    symbol: "KWD",
  },
  {
    code: "KG",
    country: "Kyrgyzstan",
    name: "Kyrgyzstan (лв)",
    currency: "KGS",
    symbol: "лв",
  },
  {
    code: "LA",
    country: "Lao People's Democratic Republic",
    name: "Lao People's Democratic Republic (₭)",
    currency: "LAK",
    symbol: "₭",
  },
  {
    code: "LV",
    country: "Latvia",
    name: "Latvia (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "LB",
    country: "Lebanon",
    name: "Lebanon (£)",
    currency: "LBP",
    symbol: "£",
  },
  {
    code: "LS",
    country: "Lesotho",
    name: "Lesotho (LSL)",
    currency: "LSL",
    symbol: "LSL",
  },
  {
    code: "LR",
    country: "Liberia",
    name: "Liberia ($)",
    currency: "LRD",
    symbol: "$",
  },
  {
    code: "LY",
    country: "Libya",
    name: "Libya (LYD)",
    currency: "LYD",
    symbol: "LYD",
  },
  {
    code: "LI",
    country: "Liechtenstein",
    name: "Liechtenstein (CHF)",
    currency: "CHF",
    symbol: "CHF",
  },
  {
    code: "LT",
    country: "Lithuania",
    name: "Lithuania (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "LU",
    country: "Luxembourg",
    name: "Luxembourg (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "MO",
    country: "Macao",
    name: "Macao (MOP)",
    currency: "MOP",
    symbol: "MOP",
  },
  {
    code: "MK",
    country: "Macedonia, The Former Yugoslav Republic Of",
    name: "Macedonia, The Former Yugoslav Republic Of (ден)",
    currency: "MKD",
    symbol: "ден",
  },
  {
    code: "MG",
    country: "Madagascar",
    name: "Madagascar (MGA)",
    currency: "MGA",
    symbol: "MGA",
  },
  {
    code: "MW",
    country: "Malawi",
    name: "Malawi (MWK)",
    currency: "MWK",
    symbol: "MWK",
  },
  {
    code: "MY",
    country: "Malaysia",
    name: "Malaysia (RM)",
    currency: "MYR",
    symbol: "RM",
  },
  {
    code: "MV",
    country: "Maldives",
    name: "Maldives (MVR)",
    currency: "MVR",
    symbol: "MVR",
  },
  {
    code: "ML",
    country: "Mali",
    name: "Mali (XOF)",
    currency: "XOF",
    symbol: "XOF",
  },
  {
    code: "MT",
    country: "Malta",
    name: "Malta (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "MH",
    country: "Marshall Islands",
    name: "Marshall Islands ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "MQ",
    country: "Martinique",
    name: "Martinique (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "MR",
    country: "Mauritania",
    name: "Mauritania (MRO)",
    currency: "MRO",
    symbol: "MRO",
  },
  {
    code: "MU",
    country: "Mauritius",
    name: "Mauritius (₨)",
    currency: "MUR",
    symbol: "₨",
  },
  {
    code: "YT",
    country: "Mayotte",
    name: "Mayotte (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "MX",
    country: "Mexico",
    name: "Mexico ($)",
    currency: "MXN",
    symbol: "$",
  },
  {
    code: "FM",
    country: "Micronesia, Federated States Of",
    name: "Micronesia, Federated States Of ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "MD",
    country: "Moldova",
    name: "Moldova (MDL)",
    currency: "MDL",
    symbol: "MDL",
  },
  {
    code: "MC",
    country: "Monaco",
    name: "Monaco (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "MN",
    country: "Mongolia",
    name: "Mongolia (₮)",
    currency: "MNT",
    symbol: "₮",
  },
  {
    code: "ME",
    country: "Montenegro",
    name: "Montenegro (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "MS",
    country: "Montserrat",
    name: "Montserrat ($)",
    currency: "XCD",
    symbol: "$",
  },
  {
    code: "MA",
    country: "Morocco",
    name: "Morocco (MAD)",
    currency: "MAD",
    symbol: "MAD",
  },
  {
    code: "MZ",
    country: "Mozambique",
    name: "Mozambique (MT)",
    currency: "MZN",
    symbol: "MT",
  },
  {
    code: "MM",
    country: "Myanmar",
    name: "Myanmar (MMK)",
    currency: "MMK",
    symbol: "MMK",
  },
  {
    code: "NA",
    country: "Namibia",
    name: "Namibia ($)",
    currency: "NAD",
    symbol: "$",
  },
  {
    code: "NR",
    country: "Nauru",
    name: "Nauru ($)",
    currency: "AUD",
    symbol: "$",
  },
  {
    code: "NP",
    country: "Nepal",
    name: "Nepal (₨)",
    currency: "NPR",
    symbol: "₨",
  },
  {
    code: "NL",
    country: "Netherlands",
    name: "Netherlands (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "NC",
    country: "New Caledonia",
    name: "New Caledonia (XPF)",
    currency: "XPF",
    symbol: "XPF",
  },
  {
    code: "NZ",
    country: "New Zealand",
    name: "New Zealand ($)",
    currency: "NZD",
    symbol: "$",
  },
  {
    code: "NI",
    country: "Nicaragua",
    name: "Nicaragua (C$)",
    currency: "NIO",
    symbol: "C$",
  },
  {
    code: "NE",
    country: "Niger",
    name: "Niger (XOF)",
    currency: "XOF",
    symbol: "XOF",
  },
  {
    code: "NG",
    country: "Nigeria",
    name: "Nigeria (₦)",
    currency: "NGN",
    symbol: "₦",
  },
  {
    code: "NU",
    country: "Niue",
    name: "Niue ($)",
    currency: "NZD",
    symbol: "$",
  },
  {
    code: "NF",
    country: "Norfolk Island",
    name: "Norfolk Island ($)",
    currency: "AUD",
    symbol: "$",
  },
  {
    code: "MP",
    country: "Northern Mariana Islands",
    name: "Northern Mariana Islands ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "NO",
    country: "Norway",
    name: "Norway (kr)",
    currency: "NOK",
    symbol: "kr",
  },
  {
    code: "OM",
    country: "Oman",
    name: "Oman (﷼)",
    currency: "OMR",
    symbol: "﷼",
  },
  {
    code: "PK",
    country: "Pakistan",
    name: "Pakistan (₨)",
    currency: "PKR",
    symbol: "₨",
  },
  {
    code: "PW",
    country: "Palau",
    name: "Palau ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "PS",
    country: "Palestinian Territory, Occupied",
    name: "Palestinian Territory, Occupied (JOD)",
    currency: "JOD",
    symbol: "JOD",
  },
  {
    code: "PA",
    country: "Panama",
    name: "Panama (B/.)",
    currency: "PAB",
    symbol: "B/.",
  },
  {
    code: "PG",
    country: "Papua New Guinea",
    name: "Papua New Guinea (PGK)",
    currency: "PGK",
    symbol: "PGK",
  },
  {
    code: "PY",
    country: "Paraguay",
    name: "Paraguay (Gs)",
    currency: "PYG",
    symbol: "Gs",
  },
  {
    code: "PE",
    country: "Peru",
    name: "Peru (S/.)",
    currency: "PEN",
    symbol: "S/.",
  },
  {
    code: "PH",
    country: "Philippines",
    name: "Philippines (₱)",
    currency: "PHP",
    symbol: "₱",
  },
  {
    code: "PN",
    country: "Pitcairn",
    name: "Pitcairn ($)",
    currency: "NZD",
    symbol: "$",
  },
  {
    code: "PL",
    country: "Poland",
    name: "Poland (zł)",
    currency: "PLN",
    symbol: "zł",
  },
  {
    code: "PT",
    country: "Portugal",
    name: "Portugal (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "PR",
    country: "Puerto Rico",
    name: "Puerto Rico ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "QA",
    country: "Qatar",
    name: "Qatar (﷼)",
    currency: "QAR",
    symbol: "﷼",
  },
  {
    code: "CG",
    country: "Republic Of Congo",
    name: "Republic Of Congo (XAF)",
    currency: "XAF",
    symbol: "XAF",
  },
  {
    code: "RE",
    country: "Reunion",
    name: "Reunion (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "RO",
    country: "Romania",
    name: "Romania (lei)",
    currency: "RON",
    symbol: "lei",
  },
  {
    code: "RU",
    country: "Russian Federation",
    name: "Russian Federation (₽)",
    currency: "RUB",
    symbol: "₽",
  },
  {
    code: "RW",
    country: "Rwanda",
    name: "Rwanda (RWF)",
    currency: "RWF",
    symbol: "RWF",
  },
  {
    code: "BL",
    country: "Saint Barthélemy",
    name: "Saint Barthélemy (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "SH",
    country: "Saint Helena, Ascension And Tristan Da Cunha",
    name: "Saint Helena, Ascension And Tristan Da Cunha (£)",
    currency: "SHP",
    symbol: "£",
  },
  {
    code: "KN",
    country: "Saint Kitts And Nevis",
    name: "Saint Kitts And Nevis ($)",
    currency: "XCD",
    symbol: "$",
  },
  {
    code: "LC",
    country: "Saint Lucia",
    name: "Saint Lucia ($)",
    currency: "XCD",
    symbol: "$",
  },
  {
    code: "MF",
    country: "Saint Martin",
    name: "Saint Martin (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "PM",
    country: "Saint Pierre And Miquelon",
    name: "Saint Pierre And Miquelon (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "VC",
    country: "Saint Vincent And The Grenadines",
    name: "Saint Vincent And The Grenadines ($)",
    currency: "XCD",
    symbol: "$",
  },
  {
    code: "WS",
    country: "Samoa",
    name: "Samoa (WST)",
    currency: "WST",
    symbol: "WST",
  },
  {
    code: "SM",
    country: "San Marino",
    name: "San Marino (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "ST",
    country: "Sao Tome and Principe",
    name: "Sao Tome and Principe (STD)",
    currency: "STD",
    symbol: "STD",
  },
  {
    code: "SA",
    country: "Saudi Arabia",
    name: "Saudi Arabia (﷼)",
    currency: "SAR",
    symbol: "﷼",
  },
  {
    code: "SN",
    country: "Senegal",
    name: "Senegal (XOF)",
    currency: "XOF",
    symbol: "XOF",
  },
  {
    code: "RS",
    country: "Serbia",
    name: "Serbia (Дин.)",
    currency: "RSD",
    symbol: "Дин.",
  },
  {
    code: "SC",
    country: "Seychelles",
    name: "Seychelles (₨)",
    currency: "SCR",
    symbol: "₨",
  },
  {
    code: "SL",
    country: "Sierra Leone",
    name: "Sierra Leone (SLL)",
    currency: "SLL",
    symbol: "SLL",
  },
  {
    code: "SG",
    country: "Singapore",
    name: "Singapore ($)",
    currency: "SGD",
    symbol: "$",
  },
  {
    code: "SX",
    country: "Sint Maarten",
    name: "Sint Maarten (ƒ)",
    currency: "ANG",
    symbol: "ƒ",
  },
  {
    code: "SK",
    country: "Slovakia",
    name: "Slovakia (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "SI",
    country: "Slovenia",
    name: "Slovenia (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "SB",
    country: "Solomon Islands",
    name: "Solomon Islands ($)",
    currency: "SBD",
    symbol: "$",
  },
  {
    code: "SO",
    country: "Somalia",
    name: "Somalia (S)",
    currency: "SOS",
    symbol: "S",
  },
  {
    code: "ZA",
    country: "South Africa",
    name: "South Africa (R)",
    currency: "ZAR",
    symbol: "R",
  },
  {
    code: "GS",
    country: "South Georgia And The South Sandwich Islands",
    name: "South Georgia And The South Sandwich Islands (£)",
    currency: "GBP",
    symbol: "£",
  },
  {
    code: "SS",
    country: "South Sudan",
    name: "South Sudan (SSP)",
    currency: "SSP",
    symbol: "SSP",
  },
  {
    code: "ES",
    country: "Spain",
    name: "Spain (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "LK",
    country: "Sri Lanka",
    name: "Sri Lanka (₨)",
    currency: "LKR",
    symbol: "₨",
  },
  {
    code: "SD",
    country: "Sudan",
    name: "Sudan (SDG)",
    currency: "SDG",
    symbol: "SDG",
  },
  {
    code: "SR",
    country: "Suriname",
    name: "Suriname ($)",
    currency: "SRD",
    symbol: "$",
  },
  {
    code: "SJ",
    country: "Svalbard And Jan Mayen",
    name: "Svalbard And Jan Mayen (kr)",
    currency: "NOK",
    symbol: "kr",
  },
  {
    code: "SZ",
    country: "Swaziland",
    name: "Swaziland (SZL)",
    currency: "SZL",
    symbol: "SZL",
  },
  {
    code: "SE",
    country: "Sweden",
    name: "Sweden (kr)",
    currency: "SEK",
    symbol: "kr",
  },
  {
    code: "CH",
    country: "Switzerland",
    name: "Switzerland (CHF)",
    currency: "CHF",
    symbol: "CHF",
  },
  {
    code: "SY",
    country: "Syrian Arab Republic",
    name: "Syrian Arab Republic (£)",
    currency: "SYP",
    symbol: "£",
  },
  {
    code: "TW",
    country: "Taiwan",
    name: "Taiwan (NT$)",
    currency: "TWD",
    symbol: "NT$",
  },
  {
    code: "TJ",
    country: "Tajikistan",
    name: "Tajikistan (TJS)",
    currency: "TJS",
    symbol: "TJS",
  },
  {
    code: "TZ",
    country: "Tanzania, United Republic Of",
    name: "Tanzania, United Republic Of (TSh)",
    currency: "TZS",
    symbol: "TSh",
  },
  {
    code: "TH",
    country: "Thailand",
    name: "Thailand (฿)",
    currency: "THB",
    symbol: "฿",
  },
  {
    code: "TL",
    country: "Timor-Leste, Democratic Republic of",
    name: "Timor-Leste, Democratic Republic of ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "TG",
    country: "Togo",
    name: "Togo (XOF)",
    currency: "XOF",
    symbol: "XOF",
  },
  {
    code: "TK",
    country: "Tokelau",
    name: "Tokelau ($)",
    currency: "NZD",
    symbol: "$",
  },
  {
    code: "TO",
    country: "Tonga",
    name: "Tonga (TOP)",
    currency: "TOP",
    symbol: "TOP",
  },
  {
    code: "TT",
    country: "Trinidad And Tobago",
    name: "Trinidad And Tobago (TT$)",
    currency: "TTD",
    symbol: "TT$",
  },
  {
    code: "TN",
    country: "Tunisia",
    name: "Tunisia (TND)",
    currency: "TND",
    symbol: "TND",
  },
  {
    code: "TR",
    country: "Turkey",
    name: "Turkey (TRY)",
    currency: "TRY",
    symbol: "TRY",
  },
  {
    code: "TM",
    country: "Turkmenistan",
    name: "Turkmenistan (TMT)",
    currency: "TMT",
    symbol: "TMT",
  },
  {
    code: "TC",
    country: "Turks And Caicos Islands",
    name: "Turks And Caicos Islands ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "TV",
    country: "Tuvalu",
    name: "Tuvalu ($)",
    currency: "AUD",
    symbol: "$",
  },
  {
    code: "UG",
    country: "Uganda",
    name: "Uganda (USh)",
    currency: "UGX",
    symbol: "USh",
  },
  {
    code: "UA",
    country: "Ukraine",
    name: "Ukraine (₴)",
    currency: "UAH",
    symbol: "₴",
  },
  {
    code: "AE",
    country: "United Arab Emirates",
    name: "United Arab Emirates (AED)",
    currency: "AED",
    symbol: "AED",
  },
  {
    code: "GB",
    country: "United Kingdom",
    name: "United Kingdom (£)",
    currency: "GBP",
    symbol: "£",
  },
  {
    code: "US",
    country: "United States",
    name: "United States ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "UM",
    country: "United States Minor Outlying Islands",
    name: "United States Minor Outlying Islands ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "UY",
    country: "Uruguay",
    name: "Uruguay ($U)",
    currency: "UYU",
    symbol: "$U",
  },
  {
    code: "UZ",
    country: "Uzbekistan",
    name: "Uzbekistan (лв)",
    currency: "UZS",
    symbol: "лв",
  },
  {
    code: "VU",
    country: "Vanuatu",
    name: "Vanuatu (VUV)",
    currency: "VUV",
    symbol: "VUV",
  },
  {
    code: "VA",
    country: "Vatican City State",
    name: "Vatican City State (€)",
    currency: "EUR",
    symbol: "€",
  },
  {
    code: "VE",
    country: "Venezuela, Bolivarian Republic Of",
    name: "Venezuela, Bolivarian Republic Of (Bs)",
    currency: "VEF",
    symbol: "Bs",
  },
  {
    code: "VN",
    country: "Viet Nam",
    name: "Viet Nam (₫)",
    currency: "VND",
    symbol: "₫",
  },
  {
    code: "VG",
    country: "Virgin Islands (British)",
    name: "Virgin Islands (British) ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "VI",
    country: "Virgin Islands (US)",
    name: "Virgin Islands (US) ($)",
    currency: "USD",
    symbol: "$",
  },
  {
    code: "WF",
    country: "Wallis And Futuna",
    name: "Wallis And Futuna (XPF)",
    currency: "XPF",
    symbol: "XPF",
  },
  {
    code: "EH",
    country: "Western Sahara",
    name: "Western Sahara (MAD)",
    currency: "MAD",
    symbol: "MAD",
  },
  {
    code: "YE",
    country: "Yemen",
    name: "Yemen (﷼)",
    currency: "YER",
    symbol: "﷼",
  },
  {
    code: "ZM",
    country: "Zambia",
    name: "Zambia (ZMW)",
    currency: "ZMW",
    symbol: "ZMW",
  },
  {
    code: "ZW",
    country: "Zimbabwe",
    name: "Zimbabwe ($)",
    currency: "USD",
    symbol: "$",
  },
];
