/** Defensive input bounds for typography fields (characters). */
export const FIELD_LIMITS = {
  businessName: 80,
  businessAddress: 240,
  businessPhone: 40,
  businessEmail: 80,
  businessWebsite: 120,
  businessTaxId: 40,
  businessRegId: 40,
  invoiceLabel: 32,
  invoiceNumber: 40,
  customerName: 80,
  customerCompany: 80,
  customerEmail: 80,
  customerPhone: 40,
  customerAddress: 240,
  customerTaxId: 40,
  itemName: 120,
  itemDescription: 280,
  paymentInstructions: 400,
  terms: 600,
  notes: 400,
  watermarkText: 40,
};
