/** Defensive input bounds for text and typography parameters (characters). */
export const FIELD_LIMITS = {
  businessName: 60,
  businessAddress: 180,
  businessPhone: 30,
  businessEmail: 60,
  invoiceLabel: 20,
  invoiceNumber: 30,
  customerName: 60,
  customerCompany: 60,
  customerAddress: 180,
  customerTaxId: 35,
  businessTaxId: 35,
  businessRegId: 35,
  taxName: 15,
  itemName: 80,
  itemDescription: 200,
  paymentInstructions: 350,
  terms: 450,
  notes: 300,
};
